
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author apoor
 */
public class MAIN_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_WINDOW
     */
    public MAIN_WINDOW() {
        initComponents();
         jLabel_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu2.png")));
        // set border to the menu items
          Border menu_items_border = BorderFactory.createMatteBorder (0, 0, 1, 0, Color.red);
          jLabel_property.setBorder (menu_items_border);
          jLabel_propertyType.setBorder (menu_items_border);
          jLabel_propertyImages.setBorder (menu_items_border);
          jLabel_clients.setBorder (menu_items_border);
          jLabel_owner.setBorder (menu_items_border);
           jLabel_sale.setBorder (menu_items_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_menu = new javax.swing.JLabel();
        jLabel_propertyType = new javax.swing.JLabel();
        jLabel_propertyImages = new javax.swing.JLabel();
        jLabel_owner = new javax.swing.JLabel();
        jLabel_property = new javax.swing.JLabel();
        jLabel_clients = new javax.swing.JLabel();
        jLabel_sale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel_menu.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel_menu.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_menu.setText(" MAIN MENU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_propertyType.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel_propertyType.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_propertyType.setText("PROPERTY-TYPE");
        jLabel_propertyType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_propertyType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyTypeMouseExited(evt);
            }
        });

        jLabel_propertyImages.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel_propertyImages.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_propertyImages.setText("PROPERTY-IMAGES");
        jLabel_propertyImages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_propertyImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyImagesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyImagesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyImagesMouseExited(evt);
            }
        });

        jLabel_owner.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel_owner.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_owner.setText(" OWNER");
        jLabel_owner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_owner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ownerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ownerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ownerMouseExited(evt);
            }
        });

        jLabel_property.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel_property.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_property.setText("PROPERTY");
        jLabel_property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseExited(evt);
            }
        });

        jLabel_clients.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel_clients.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_clients.setText(" CLIENTS");
        jLabel_clients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clientsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_clientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_clientsMouseExited(evt);
            }
        });

        jLabel_sale.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel_sale.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_sale.setText("  SALE");
        jLabel_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_owner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_propertyImages, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(jLabel_propertyType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_property, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                    .addComponent(jLabel_clients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jLabel_sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel_property, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_propertyType, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_propertyImages, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_owner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_clients, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 761, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_saleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseExited

        jLabel_sale.setBackground (Color.red);
        jLabel_sale. setForeground (Color.red);

    }//GEN-LAST:event_jLabel_saleMouseExited

    private void jLabel_saleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseEntered

        jLabel_sale.setBackground (Color.red);
        jLabel_sale. setForeground (Color.white);

    }//GEN-LAST:event_jLabel_saleMouseEntered

    private void jLabel_clientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientsMouseExited

        jLabel_clients.setBackground (Color.red);
        jLabel_clients. setForeground (Color.red);

    }//GEN-LAST:event_jLabel_clientsMouseExited

    private void jLabel_clientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientsMouseEntered

        jLabel_clients.setBackground (Color.red);
        jLabel_clients. setForeground (Color.white);

    }//GEN-LAST:event_jLabel_clientsMouseEntered

    private void jLabel_propertyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseExited

        jLabel_property.setBackground (Color.red);
        jLabel_property. setForeground (Color.red);

    }//GEN-LAST:event_jLabel_propertyMouseExited

    private void jLabel_propertyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseEntered

        jLabel_property.setBackground (Color.red);
        jLabel_property. setForeground (Color.white);
    }//GEN-LAST:event_jLabel_propertyMouseEntered

    private void jLabel_ownerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ownerMouseExited

        jLabel_owner.setBackground (Color.red);
        jLabel_owner. setForeground (Color.red);

    }//GEN-LAST:event_jLabel_ownerMouseExited

    private void jLabel_ownerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ownerMouseEntered

        jLabel_owner.setBackground (Color.red);
        jLabel_owner. setForeground (Color.white);

    }//GEN-LAST:event_jLabel_ownerMouseEntered

    private void jLabel_propertyImagesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyImagesMouseExited

        jLabel_propertyImages.setBackground (Color.red);
        jLabel_propertyImages. setForeground (Color.red);

    }//GEN-LAST:event_jLabel_propertyImagesMouseExited

    private void jLabel_propertyImagesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyImagesMouseEntered

        jLabel_propertyImages.setBackground (Color.red);
        jLabel_propertyImages. setForeground (Color.white);

    }//GEN-LAST:event_jLabel_propertyImagesMouseEntered

    private void jLabel_propertyTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyTypeMouseExited

        jLabel_propertyType.setBackground (Color.red);
        jLabel_propertyType. setForeground (Color.red);

    }//GEN-LAST:event_jLabel_propertyTypeMouseExited

    private void jLabel_propertyTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyTypeMouseEntered

        jLabel_propertyType.setBackground (Color.red);
        jLabel_propertyType. setForeground (Color.white);

    }//GEN-LAST:event_jLabel_propertyTypeMouseEntered

    private void jLabel_propertyTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyTypeMouseClicked
          PROPERTY_TYPE_WINDOW typeform = new PROPERTY_TYPE_WINDOW();
                 typeform.setVisible(true);
                 typeform.pack();
                 typeform.setLocationRelativeTo(null);
                 typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_propertyTypeMouseClicked

    private void jLabel_ownerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ownerMouseClicked
                 OWNER_WINDOW ownerform = new OWNER_WINDOW();
                 ownerform.setVisible(true);
                 ownerform.pack();
                 ownerform.setLocationRelativeTo(null);
                 ownerform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);    }//GEN-LAST:event_jLabel_ownerMouseClicked

    private void jLabel_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientsMouseClicked
        CLIENT_WINDOW clientform = new CLIENT_WINDOW();
                 clientform.setVisible(true);
                 clientform.pack();
                 clientform.setLocationRelativeTo(null);
                 clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_clientsMouseClicked

    private void jLabel_propertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseClicked
        PROPERTY_WINDOW propertyform = new PROPERTY_WINDOW();
                 propertyform.setVisible(true);
                propertyform.pack();
                 propertyform.setLocationRelativeTo(null);
                 propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_propertyMouseClicked

    private void jLabel_propertyImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyImagesMouseClicked
        PROPERTY_IMAGES_WINDOW propertyform = new PROPERTY_IMAGES_WINDOW();
                 propertyform.setVisible(true);
                propertyform.pack();
                 propertyform.setLocationRelativeTo(null);
                 propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_propertyImagesMouseClicked

    private void jLabel_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseClicked
         SALE_WINDOW saleform = new SALE_WINDOW();
                 saleform.setVisible(true);
                 saleform.pack();
                 saleform.setLocationRelativeTo(null);
                 saleform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_saleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_clients;
    private javax.swing.JLabel jLabel_menu;
    private javax.swing.JLabel jLabel_owner;
    private javax.swing.JLabel jLabel_property;
    private javax.swing.JLabel jLabel_propertyImages;
    private javax.swing.JLabel jLabel_propertyType;
    private javax.swing.JLabel jLabel_sale;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
